INFO - Aggregating data for CPAN
INFO - CPAN aggregator has been printed
INFO - CPAN_A10PLUS_B10PLUS aggregator has been printed
INFO - Aggregating data for CRAN
INFO - CRAN aggregator has been printed
INFO - CRAN_A10PLUS_B10PLUS aggregator has been printed
INFO - Aggregating data for Dub
INFO - Dub aggregator has been printed
INFO - Dub_A10PLUS_B10PLUS aggregator has been printed
INFO - Aggregating data for Elm
INFO - Elm aggregator has been printed
INFO - Elm_A10PLUS_B10PLUS aggregator has been printed
INFO - Aggregating data for Haxelib
ERROR - org.postgresql.util.PSQLException: ERROR: column "ownerwithname" does not exist
  Position: 18
ERROR - org.postgresql.util.PSQLException: ERROR: column "ownerwithname" does not exist
  Position: 18
INFO - Haxelib aggregator has been printed
INFO - Haxelib_A10PLUS_B10PLUS aggregator has been printed
INFO - Aggregating data for Homebrew
INFO - Homebrew aggregator has been printed
INFO - Homebrew_A10PLUS_B10PLUS aggregator has been printed
INFO - Aggregating data for Pub
ERROR - org.postgresql.util.PSQLException: ERROR: column "ownerwithname" does not exist
  Position: 18
ERROR - org.postgresql.util.PSQLException: ERROR: column "ownerwithname" does not exist
  Position: 18
INFO - Pub aggregator has been printed
INFO - Pub_A10PLUS_B10PLUS aggregator has been printed
INFO - Aggregating data for Puppet
ERROR - org.postgresql.util.PSQLException: ERROR: column "ownerwithname" does not exist
  Position: 18
ERROR - org.postgresql.util.PSQLException: ERROR: column "ownerwithname" does not exist
  Position: 18
ERROR - org.postgresql.util.PSQLException: ERROR: column "ownerwithname" does not exist
  Position: 18
ERROR - org.postgresql.util.PSQLException: ERROR: column "ownerwithname" does not exist
  Position: 18
INFO - Puppet aggregator has been printed
INFO - Puppet_A10PLUS_B10PLUS aggregator has been printed
INFO - Aggregating data for Atom
ERROR - org.postgresql.util.PSQLException: ERROR: column "ownerwithname" does not exist
  Position: 18
ERROR - org.postgresql.util.PSQLException: ERROR: column "ownerwithname" does not exist
  Position: 18
